version: "3.9"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Travianer1
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306


  intranet-backend:
    image: intranet-backend
    restart: always
    ports:
      - 3001:3001


  intranet-frontend:
    image: intranet-frontend
    ports:
      - 80:80


